data:
    corpus_1:
        path_src: ../synpos/data/java-med-processed/train_src.txt
        path_tgt: ../synpos/data/java-med/java-med.TargetType.seq.train.target.txt
        src_feats:
            feat_0: ../synpos/data/java-med-processed/train_feat0.txt
            feat_1: ../synpos/data/java-med-processed/train_feat1.txt
            feat_2: ../synpos/data/java-med-processed/train_feat2.txt
            feat_3: ../synpos/data/java-med-processed/train_feat3.txt
            feat_4: ../synpos/data/java-med-processed/train_feat4.txt
            feat_5: ../synpos/data/java-med-processed/train_feat5.txt
            feat_6: ../synpos/data/java-med-processed/train_feat6.txt
            feat_7: ../synpos/data/java-med-processed/train_feat7.txt
            feat_8: ../synpos/data/java-med-processed/train_feat8.txt
            feat_9: ../synpos/data/java-med-processed/train_feat9.txt
            feat_10: ../synpos/data/java-med-processed/train_feat10.txt
            feat_11: ../synpos/data/java-med-processed/train_feat11.txt
            feat_12: ../synpos/data/java-med-processed/train_feat12.txt
            feat_13: ../synpos/data/java-med-processed/train_feat13.txt
            feat_14: ../synpos/data/java-med-processed/train_feat14.txt
            feat_15: ../synpos/data/java-med-processed/train_feat15.txt
            feat_16: ../synpos/data/java-med-processed/train_feat16.txt
            feat_17: ../synpos/data/java-med-processed/train_feat17.txt
            feat_18: ../synpos/data/java-med-processed/train_feat18.txt
            feat_19: ../synpos/data/java-med-processed/train_feat19.txt
            feat_20: ../synpos/data/java-med-processed/train_feat20.txt
            feat_21: ../synpos/data/java-med-processed/train_feat21.txt
            feat_22: ../synpos/data/java-med-processed/train_feat22.txt
            feat_23: ../synpos/data/java-med-processed/train_feat23.txt
        transforms: [filterfeats, onmt_tokenize, inferfeats] #, filtertoolong]
        weight: 1
    valid:
        path_src: ../synpos/data/java-med-processed/val_src.txt
        path_tgt: ../synpos/data/java-med/java-med.TargetType.seq.val.target.txt
        src_feats:
            feat_0: ../synpos/data/java-med-processed/val_feat0.txt
            feat_1: ../synpos/data/java-med-processed/val_feat1.txt
            feat_2: ../synpos/data/java-med-processed/val_feat2.txt
            feat_3: ../synpos/data/java-med-processed/val_feat3.txt
            feat_4: ../synpos/data/java-med-processed/val_feat4.txt
            feat_5: ../synpos/data/java-med-processed/val_feat5.txt
            feat_6: ../synpos/data/java-med-processed/val_feat6.txt
            feat_7: ../synpos/data/java-med-processed/val_feat7.txt
            feat_8: ../synpos/data/java-med-processed/val_feat8.txt
            feat_9: ../synpos/data/java-med-processed/val_feat9.txt
            feat_10: ../synpos/data/java-med-processed/val_feat10.txt
            feat_11: ../synpos/data/java-med-processed/val_feat11.txt
            feat_12: ../synpos/data/java-med-processed/val_feat12.txt
            feat_13: ../synpos/data/java-med-processed/val_feat13.txt
            feat_14: ../synpos/data/java-med-processed/val_feat14.txt
            feat_15: ../synpos/data/java-med-processed/val_feat15.txt
            feat_16: ../synpos/data/java-med-processed/val_feat16.txt
            feat_17: ../synpos/data/java-med-processed/val_feat17.txt
            feat_18: ../synpos/data/java-med-processed/val_feat18.txt
            feat_19: ../synpos/data/java-med-processed/val_feat19.txt
            feat_20: ../synpos/data/java-med-processed/val_feat20.txt
            feat_21: ../synpos/data/java-med-processed/val_feat21.txt
            feat_22: ../synpos/data/java-med-processed/val_feat22.txt
            feat_23: ../synpos/data/java-med-processed/val_feat23.txt
        transforms: [filterfeats, onmt_tokenize, inferfeats]

src_onmttok_kwargs: "{'mode': 'space'}"
tgt_onmttok_kwargs: "{'mode': 'space'}"

# # Vocab opts
src_vocab: java_med/data_shared/data.vocab.src
tgt_vocab: java_med/data_shared/data.vocab.src
src_feats_vocab:
    feat_0: java_med/data/vocab/data.vocab.feat_0
    feat_1: java_med/data/vocab/data.vocab.feat_1
    feat_2: java_med/data/vocab/data.vocab.feat_2
    feat_3: java_med/data/vocab/data.vocab.feat_3
    feat_4: java_med/data/vocab/data.vocab.feat_4
    feat_5: java_med/data/vocab/data.vocab.feat_5
    feat_6: java_med/data/vocab/data.vocab.feat_6
    feat_7: java_med/data/vocab/data.vocab.feat_7
    feat_8: java_med/data/vocab/data.vocab.feat_8
    feat_9: java_med/data/vocab/data.vocab.feat_9
    feat_10: java_med/data/vocab/data.vocab.feat_10
    feat_11: java_med/data/vocab/data.vocab.feat_11
    feat_12: java_med/data/vocab/data.vocab.feat_12
    feat_13: java_med/data/vocab/data.vocab.feat_13
    feat_14: java_med/data/vocab/data.vocab.feat_14
    feat_15: java_med/data/vocab/data.vocab.feat_15
    feat_16: java_med/data/vocab/data.vocab.feat_16
    feat_17: java_med/data/vocab/data.vocab.feat_17
    feat_18: java_med/data/vocab/data.vocab.feat_18
    feat_19: java_med/data/vocab/data.vocab.feat_19
    feat_20: java_med/data/vocab/data.vocab.feat_20
    feat_21: java_med/data/vocab/data.vocab.feat_21
    feat_22: java_med/data/vocab/data.vocab.feat_22
    feat_23: java_med/data/vocab/data.vocab.feat_23
feat_merge: 'sharemlp'
src_vocab_size: 2000
share_vocab: True
copy_attn: True

save_data: java_med_data
overwrite: False

save_checkpoint_steps: 1000
keep_checkpoint: 30
seed: 3435
train_steps: 600000
valid_steps: 1000
warmup_steps: 8000
report_every: 100
# Uri:
#early_stopping: 10
#early_stopping_criteria: accuracy

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
#position_encoding: 'true'

world_size: 2
gpu_ranks:
- 0
- 1

